services:
  - type: web
    name: inventory-management
    env: python
    plan: free
    
    buildCommand: pip install -r requirements.txt
    buildPlan: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 app:app
    
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        fromBuild: true
      - key: DB_HOST
        fromBuild: true
      - key: DB_USER
        fromBuild: true
      - key: DB_PASSWORD
        fromBuild: true
      - key: DB_NAME
        value: inventory_db_e9kn
      - key: DB_PORT
        value: "5432"
